language: go

env:
  global:
    - GO111MODULE=on
  matrix:
    - MAKE_TASK=lintall
    - MAKE_TASK=integration

go:
  - 1.12.9
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

script:
  - make $MAKE_TASK
